Repository aaradhyabansal/open-source--contri, pull requests merged in 2022-10, with the labels that each got.

#1 create binarytree.cpp
  binarytree.cpp
Labels: hacktoberfest

#2 create circularlist.cp
  circularlistque.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 Create concatinatecircularlist.cpp
  concatcircylarlinkedlist
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 Create multiply2polynomials
  multiply2polynomials
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#6 Create deleteduplicste.cpp
  deleteduplicste.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#9 Create multiplyrecursion.cpp
  multiplyrecursion.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#10 Update lcmrecursion.cpp
  lcmrecursion.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#11 Create SumPowerSeriesRecursion.cpp
  SumPowerSeriesRecursion.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#12 Create linearsearch.cpp
  linearsearch.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#14 Create binarysearchiterative.cpp
  binarysearchiterative.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#15 Create kthsmallest.cpp
  kthsmallest.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#16 Create interpolationsearch.cpp
  interpolationsearch.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#18 Create indexofchar.cpp
  indexofchar.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#19 Create missing.cpp
  missing.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#20 Create ceilfloor.cpp
  ceilfloor.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#21 Create DiffIfexists.cpp
  DiffIfexists.cpp
Labels: good first issue, invalid, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, spam

#24 Create petrolpumpqueue.cpp
  petrolpumpqueue.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Create radius.cpp
  radius.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Create lolympics.cpp
  lolympics.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Create stringpermutations.cpp
  stringpermutations.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#29 Create inversioncount.cpp
  inversioncount.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 Create kthsamllest.cpp
  kthsamllest.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Create minswap.cpp
  minswap.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#32 Create sortstack.cpp
  sortstack.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#33 Create palindromicpermutations.cpp
  palindromicpermutations.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#34 Create reversestring.cpp
  reversestring.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Create towerofhanoi.cpp
  towerofhanoi.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#36 Create halistonesequence.cpp
  halistonesequence.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#37 Quick sort, Hacktoberfest2022
  Quicksort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 adding greatest_in_array and search_in_array
  greatest_in_array.cpp
  search_in_array.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#39 Check if given string have balanced Parentheses
  Valid_Parentheses.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#40 Add C++ implemented digit counter
  DigitCounterusingRecursion.cpp
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
